### ISSUE TITLE
list of unions not converted to maps

### ISSUE THREAD

**Issue by alexhumphreys** [dhall-lang/dhall-json#71]
I'm writing some GoCD pipeline configs in dhall and ran into the following issue. Given this dhall file:

```
let MaterialSource =
  { mapKey : Text
  , mapValue :
    { git : Text
    , branch : Text
    }
  }
in let MaterialPipeline =
  { mapKey : Text
  , mapValue :
    { pipeline : Text
    , stage : Text
    }
  }
in let Material = < Source : MaterialSource | Pipeline : MaterialPipeline >
in let unionMaterial = constructors Material
in let Materials = List Material
in let materials : Materials =
  [ unionMaterial.Source
    { mapKey = "someRepo"
    , mapValue =
      { git = "www.example.com/user/repo.git"
      , branch = "master"
      }
    }
  , unionMaterial.Pipeline
    { mapKey = "somePipeline"
    , mapValue =
      { pipeline = "someOtherPipeline"
      , stage = "build"
      }
    }
  ]
in materials
```

I get this output:

```
- mapKey: someRepo
  mapValue:
    branch: master
    git: www.example.com/user/repo.git
- mapKey: somePipeline
  mapValue:
    stage: build
    pipeline: someOtherPipeline
```

whereas I would have expected:

```
someRepo:
    branch: master
    git: www.example.com/user/repo.git
somePipeline:
    stage: build
    pipeline: someOtherPipeline
```

I'm new to dhall so it's likely i'm doing something wrong, any help would be appreciated.
